name: Unzip File

on:
  push:
    branches:
      - main  # You can specify other branches if needed

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up unzip
      run: sudo apt-get install 

- name: Unzip file
  run: unzip resources/file.zip -d destination/folder/
      
    - name: List Unzipped Files
      run: ls destination/folder/
